import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case russian = "ru"

    var id: String { rawValue }

    var name: String {
        switch self {
        case .english: loc("English")
        case .russian: loc("Russian")
        }
    }
}

private let russianTranslations: [String: String] = [
    "English": "Английский",
    "Russian": "Русский",
    "Language": "Язык",
    "Home": "Главная",
    "Profiles": "Профили",
    "Settings": "Настройки",
    "Servers": "Серверы",
    "Personal": "Личный",
    "Profile imported": "Профиль импортирован",
    "Link not recognized": "Ссылка не распознана",
    "Import from Clipboard": "Импорт из буфера",
    "From Clipboard": "Из буфера",
    "Added: %d": "Добавлено: %d",
    "Nothing found": "Ничего не найдено",
    "QR Code from Image…": "QR-код из изображения…",
    "QR Code from Image": "QR-код из изображения",
    "Check for Updates": "Проверить обновления",
    "Select a server": "Выберите сервер",
    "Session": "Сессия",
    "Download": "Загрузка",
    "Upload": "Отдача",
    "Link or JSON": "Ссылка или JSON",
    "Subscription": "Подписка",
    "File…": "Файл…",
    "Added Manually": "Добавленные вручную",
    "No manual profiles": "Ручных профилей нет",
    "Subscriptions": "Подписки",
    "Update All": "Обновить все",
    "Add a subscription URL": "Добавьте URL подписки",
    "Add": "Добавить",
    "This subscription has no servers yet": "В этой подписке пока нет серверов",
    "Search all servers": "Поиск по всем серверам",
    "Not recognized": "Не распознано",
    "Test Latency": "Проверить задержку",
    "Edit": "Редактировать",
    "Duplicate": "Дублировать",
    "Export": "Экспорт",
    "Native Link": "Обычная ссылка",
    "QR Code…": "QR-код…",
    "Remove from Favorites": "Убрать из избранного",
    "Add to Favorites": "В избранное",
    "Delete": "Удалить",
    "Cancel": "Отмена",
    "No expiration date": "Без срока окончания",
    "Subscription expired on %@": "Подписка истекла %@",
    "Subscription expires on %@ (%d %@ remaining)": "Подписка действует до %@ (осталось: %d %@)",
    "day": "день",
    "days": "дней",
    "Appearance": "Внешний вид",
    "Routing": "Маршрутизация",
    "Automation": "Автоматизация",
    "Workspaces": "Профили пользователей",
    "Data": "Данные",
    "About": "О приложении",
    "Interface Theme": "Тема интерфейса",
    "Purple": "Фиолетовая",
    "Red": "Красная",
    "Amber": "Янтарная",
    "Mode": "Режим",
    "Global": "Глобально",
    "Rules": "По правилам",
    "Direct": "Напрямую",
    "System Proxy": "Системный прокси",
    "Connection": "Подключение",
    "Bypass LAN": "Обход LAN",
    "Connect to local devices directly": "Подключаться к локальным устройствам напрямую",
    "Kill Switch": "Аварийная блокировка",
    "Block traffic leaks if the connection drops": "Блокировать утечки при обрыве соединения",
    "Allow IPv6 inside the tunnel": "Разрешить IPv6 внутри туннеля",
    "Map DNS responses for transparent routing": "Подменять DNS для прозрачной маршрутизации",
    "Ad Blocking": "Блокировка рекламы",
    "Use geosite:category-ads-all rules": "Использовать правила geosite:category-ads-all",
    "Bypass China": "Обход Китая",
    "Route geoip:cn and geosite:cn directly": "Направлять geoip:cn и geosite:cn напрямую",
    "Blocked": "Заблокировано",
    "Apps Outside VPN": "Приложения вне VPN",
    "DNS and Geo": "DNS и Geo",
    "Secure DNS": "Защищённый DNS",
    "Send DNS queries through the VPN": "Отправлять DNS-запросы через VPN",
    "Update Geo Files": "Обновить Geo-файлы",
    "Auto Connect": "Автоподключение",
    "Connect after launch": "Подключаться после запуска",
    "Auto Reconnect": "Автопереподключение",
    "Restore the tunnel after interruption": "Восстанавливать туннель после обрыва",
    "Launch at Login": "Запускать вместе с macOS",
    "Subscription Updates": "Обновление подписок",
    "Off": "Выкл.",
    "1 Hour": "1 час",
    "6 Hours": "6 часов",
    "12 Hours": "12 часов",
    "24 Hours": "24 часа",
    "7 Days": "7 дней",
    "Latency Test": "Проверка задержки",
    "User Workspaces": "Профили пользователей",
    "Active": "Активен",
    "Switch": "Перейти",
    "Each workspace stores its own configurations, subscriptions, and active server.": "Каждый профиль хранит собственные конфигурации, подписки и активный сервер.",
    "Delete this user workspace?": "Удалить этот пользовательский профиль?",
    "Data and Diagnostics": "Данные и диагностика",
    "Create Backup": "Создать резервную копию",
    "Restore": "Восстановить",
    "Copy Log": "Копировать журнал",
    "Save Log": "Сохранить журнал",
    "Clear": "Очистить",
    "Logs will appear after connecting.": "Журнал появится после подключения.",
    "Clear the diagnostics log?": "Очистить журнал диагностики?",
    "Backup created": "Резервная копия создана",
    "Data restored": "Данные восстановлены",
    "Invalid backup": "Некорректная резервная копия",
    "A compact Xray + sing-box client for macOS": "Компактный клиент Xray + sing-box для macOS",
    "Import": "Импорт",
    "%d configurations": "%d конфигураций",
    "Link parameters verified": "Параметры ссылки проверены",
    "Format not recognized yet": "Формат пока не распознан",
    "Profile": "Профиль",
    "Name": "Название",
    "Latency": "Задержка",
    "Ping": "Пинг",
    "Server": "Сервер",
    "Port": "Порт",
    "Do not verify the TLS certificate": "Не проверять TLS-сертификат",
    "Multiplex connections": "Мультиплексировать соединения",
    "TLS Fragmentation": "Фрагментация TLS",
    "Anti-DPI ClientHello fragmentation": "Anti-DPI фрагментация ClientHello",
    "Packet Size": "Размер пакета",
    "Interval": "Интервал",
    "Secrets are hidden · edit the original link if needed": "Секреты скрыты · при необходимости измените исходную ссылку",
    "Save": "Сохранить",
    "New Subscription": "Новая подписка",
    "The name will be detected automatically from the provider response.": "Название определится автоматически из ответа провайдера.",
    "New Workspace": "Новый профиль",
    "Create": "Создать",
    "Welcome": "Добро пожаловать",
    "Add a Configuration": "Добавьте конфигурацию",
    "Allow TUN": "Разрешите TUN",
    "A compact VPN client for Xray and sing-box.": "Компактный VPN-клиент для Xray и sing-box.",
    "Paste a link or open a file, subscription, or QR code.": "Вставьте ссылку или откройте файл, подписку либо QR-код.",
    "For full-device VPN, macOS will request an administrator password. System Proxy works without it.": "Для полного VPN macOS запросит пароль администратора. Системный прокси работает без него.",
    "Back": "Назад",
    "Get Started": "Начать",
    "Next": "Далее",
    "Disconnect": "Отключиться",
    "Connect": "Подключиться",
    "Workspace": "Профиль",
    "Open": "Открыть",
    "Quit": "Завершить",
    "Disconnected": "Не подключено",
    "Connecting…": "Подключение…",
    "Protected": "Защищено",
    "Disconnecting…": "Отключение…",
    "Error": "Ошибка",
    "Workspace switched": "Профиль переключён",
    "Could not create QR code": "Не удалось создать QR-код",
    "QR code saved": "QR-код сохранён",
    "Latency test completed": "Проверка задержки завершена",
    "Test latency first": "Сначала проверьте задержку",
    "Update failed": "Ошибка обновления",
    "QR code not found": "QR-код не найден",
    "Enter the Geo file URLs": "Укажите URL Geo-файлов",
    "Geo files updated": "Geo-файлы обновлены",
    "Select System Proxy for this protocol": "Для этого протокола выберите «Системный прокси»",
    "sing-box not found": "sing-box не найден",
    "sing-box failed to start": "sing-box не запустился",
    "Connected through sing-box": "Подключено через sing-box",
    "Invalid subscription URL": "Некорректная ссылка подписки",
    "Subscription saved, but currently unavailable": "Подписка сохранена, но сейчас недоступна",
    "Could not update subscription": "Не удалось обновить подписку",
    "Add and select a server first": "Сначала добавьте и выберите сервер",
    "Xray engine not found": "Движок Xray не найден",
    "Configuration failed to start": "Конфигурация не запустилась",
    "Connected": "Подключено",
    "%@ copied": "%@ скопирован",
    "Checking…": "Проверяем…",
    "Could not apply System Proxy settings": "Не удалось применить настройки системного прокси",
    "Could not check for updates": "Не удалось проверить обновления",
    "Could not install the helper: %@": "Не удалось установить helper: %@",
    "Delete the “%@” subscription and all its servers?": "Удалить подписку «%@» и все её серверы?",
    "Delete “%@”?": "Удалить «%@»?",
    "Error: %@": "Ошибка: %@",
    "Geo: %@": "Geo: %@",
    "Latest version: %@": "Последняя версия: %@",
    "No releases yet": "Релизов пока нет",
    "No supported configurations found": "Поддерживаемые конфигурации не найдены",
    "Preparing %@ · %@:%d": "Подготовка %@ · %@:%d",
    "QR code contains no configuration": "QR-код не содержит конфигурацию",
    "QR code imported": "QR-код импортирован",
    "Restored system proxy settings after the previous shutdown": "Системные настройки прокси восстановлены после прошлого завершения",
    "Selected %@ · %d ms": "Выбран %@ · %d мс",
    "Servers added: %d": "Добавлено серверов: %d",
    "Subscription added · %d servers": "Подписка добавлена · %d серверов",
    "The local proxy did not open port %d": "Локальный прокси не открыл порт %d",
    "The provider rejected this VPN client": "Провайдер отклонил этот VPN-клиент",
    "The provider rejected this client": "Провайдер отклонил этот клиент",
    "The subscription contains no supported configurations": "В подписке нет поддерживаемых конфигураций",
    "The system helper did not respond": "Системный helper не ответил",
    "The system helper is missing from the application": "Системный helper отсутствует в приложении",
    "Unsupported sing-box profile": "Неподдерживаемый профиль sing-box",
    "Updated %d configurations": "Обновлено конфигураций: %d",
    "Xray exited with code %d": "Xray завершился с кодом %d",
    "Xray is running, but port %d is unavailable": "Xray запущен, но порт %d недоступен",
    "macOS did not allow System Proxy to be enabled": "macOS не разрешила включить системный прокси",
    "macOS: %@": "macOS: %@",
    "sing-box engine not found": "Движок sing-box не найден"
]

func loc(_ english: String) -> String {
    guard UserDefaults.standard.string(forKey: "AppLanguage") == AppLanguage.russian.rawValue else {
        return english
    }
    return russianTranslations[english] ?? english
}

func locf(_ english: String, _ arguments: CVarArg...) -> String {
    String(format: loc(english), arguments: arguments)
}
